namespace FruitsAtelier.Core;

/// <summary>Checks spacing between consecutive large catch objects generated by one slider.</summary>
public static class SliderDistanceSnap
{
    public static bool MatchesPreset(MapDocument document, double ratio)
        => Presets(document).Any(preset => Math.Abs(preset - ratio) <= 1e-4);

    private static IEnumerable<double> Presets(MapDocument document)
        => new[] { 0d }.Concat(document.DistanceSnapRatios.Take(DistanceSnap.MaximumPresets)
            .Where(value => double.IsFinite(value) && value > 0)).Distinct();

    public static IReadOnlyList<double> EndpointCandidates(MapDocument document, double wantedX,
        double scale, Func<double, double> difference)
    {
        var candidates = new List<double>();
        foreach (double signed in Presets(document).SelectMany(value => new[] { -value, value }).Distinct())
        {
            double Error(double x) => difference(x) - signed * scale;
            if (Math.Abs(Error(wantedX)) <= 1e-7) candidates.Add(wantedX);
            double left = 0, leftError = Error(left);
            if (Math.Abs(leftError) <= 1e-7) candidates.Add(left);
            // Circular control curves need not vary monotonically with endpoint X.
            // Search bounded brackets; only actual generated-event validation can accept a root.
            for (int step = 1; step <= 32; step++)
            {
                double right = step * 16, rightError = Error(right);
                if (Math.Abs(rightError) <= 1e-7) candidates.Add(right);
                if (double.IsFinite(leftError) && double.IsFinite(rightError) && leftError * rightError < 0)
                {
                    double low = left, high = right, lowError = leftError;
                    for (int i = 0; i < 35; i++)
                    {
                        double mid = (low + high) / 2, error = Error(mid);
                        if (error * lowError > 0) { low = mid; lowError = error; }
                        else high = mid;
                    }
                    candidates.Add((low + high) / 2);
                }
                left = right; leftError = rightError;
            }
        }
        return candidates.OrderBy(x => Math.Abs(x - wantedX)).DistinctBy(x => Math.Round(x, 6)).ToArray();
    }

    public static IReadOnlyDictionary<(int From, int To), double> Excesses(
        MapDocument document, IEnumerable<ConvertedCatchObject> objects, Guid sourceId)
    {
        double maximum = document.DistanceSnapRatios.Where(value => double.IsFinite(value) && value > 0)
            .Take(DistanceSnap.MaximumPresets).DefaultIfEmpty(0).Max();
        var events = objects.Where(item => item.SourceId == sourceId && item.Kind is CatchObjectKind.Fruit or CatchObjectKind.Droplet)
            .OrderBy(item => item.TimeMs).ThenBy(item => item.EventIndex).ToArray();
        var timing = new TimingMap.Lookup(document);
        var excesses = new Dictionary<(int, int), double>();
        for (int i = 1; i < events.Length; i++)
        {
            var from = events[i - 1]; var to = events[i];
            double? ratio = DistanceSnap.Ratio(new(from.TimeMs, from.X), new(to.TimeMs, to.X),
                DistanceSnap.BaseVelocity(document, from.TimeMs, timing));
            if (ratio is { } value && value > maximum + 1e-6)
                excesses[(from.EventIndex, to.EventIndex)] = value - maximum;
        }
        return excesses;
    }

    public static bool Allows(IReadOnlyDictionary<(int From, int To), double> baseline,
        IReadOnlyDictionary<(int From, int To), double> candidate)
        => candidate.All(pair => baseline.TryGetValue(pair.Key, out double old)
            && pair.Value <= old + 1e-6);

    public static IReadOnlyDictionary<(int From, int To), double> StrictErrors(
        MapDocument document, CurveTrack track, IEnumerable<ConvertedCatchObject> objects)
    {
        var events = objects.Where(item => item.SourceId == track.Id && item.Kind is CatchObjectKind.Fruit or CatchObjectKind.Droplet)
            .OrderBy(item => item.TimeMs).ThenBy(item => item.EventIndex).ToArray();
        var timing = new TimingMap.Lookup(document);
        if (track.Nodes.Count < 2) return new Dictionary<(int, int), double>();
        double start = track.Nodes[0].TimeMs, duration = track.Nodes[^1].TimeMs - start;
        var errors = new Dictionary<(int, int), double>();
        if (duration <= 0) return errors;
        for (int i = 1; i < events.Length; i++)
        {
            var from = events[i - 1]; var to = events[i];
            int fromSpan = (int)Math.Floor((from.TimeMs - start) / duration);
            int toSpan = (int)Math.Floor((Math.BitDecrement(to.TimeMs) - start) / duration);
            if (fromSpan != toSpan || fromSpan < 0 || fromSpan >= track.SpanCount) continue;
            double first = CurveMath.FirstSpanTime(track, from.TimeMs);
            double last = CurveMath.FirstSpanTime(track, to.TimeMs);
            double low = Math.Min(first, last), high = Math.Max(first, last);
            int segment = Enumerable.Range(0, track.Nodes.Count - 1).FirstOrDefault(index =>
                track.Nodes[index].TimeMs <= low + 1e-7 && track.Nodes[index + 1].TimeMs >= high - 1e-7, -1);
            if (segment < 0 || track.Nodes[segment].OutgoingCurve is not null
                || CurveMath.SegmentKind(track, segment) != CurveKind.Linear) continue;
            double? ratio = DistanceSnap.Ratio(new(from.TimeMs, from.X), new(to.TimeMs, to.X),
                DistanceSnap.BaseVelocity(document, from.TimeMs, timing));
            if (ratio is not { } value) continue;
            double error = new[] { 0d }.Concat(document.DistanceSnapRatios.Take(DistanceSnap.MaximumPresets)
                .Where(preset => double.IsFinite(preset) && preset > 0))
                .Min(preset => Math.Abs(value - preset));
            if (error > 1e-4) errors[(from.EventIndex, to.EventIndex)] = error;
        }
        return errors;
    }
}
